config/routes.rb
Rails.application.routes.draw do

  devise_for :user_account, :controllers => {
    :registrations => 'user_accounts/registrations', :sessions => 'user_accounts/sessions'}
  resources :calendar_events do
    member do
      get 'volunteer_signup'
      get 'show_volunteer_list'
      get "email_volunteer_list"
    end
  end
  root "home#index"

  resources :user_accounts do
    collection do
      get "email"
    end
    member do
      get "view"
    end
  end

  # render static pages
  controller :pages do
    get ':id', to: 'pages#show', as: 'pages'
  end


  resources :requests




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  has_and_belongs_to_many :calendar_events
  has_many :requests

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  def self.filter_on_constraints(constraints)
    filtered = UserAccount.all
    constraints.each_pair do |sym, val|
      if sym == :name
        filtered = UserAccount.where("name LIKE ?", "%#{val}%")
      elsif sym == :accounttype
        filtered = UserAccount.where("accounttype == ?", val)
      elsif sym == :fromgrade
        filtered = UserAccount.where("childgrade >= ?", val)
      elsif sym == :tograde
        filtered = UserAccount.where("childgrade <= ?", val)
      end
    end
    filtered
  end

end

app/controllers/user_accounts/confirmations_controller.rb
class UserAccounts::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/user_accounts/omniauth_callbacks_controller.rb
class UserAccounts::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/user_accounts/passwords_controller.rb
class UserAccounts::PasswordsController < Devise::PasswordsController
end

app/controllers/user_accounts/registrations_controller.rb
class UserAccounts::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  
  def destroy
      @user_account = UserAccount.find(current_user_account.id)
      if @user_account.destroy_with_password(params[:user_account][:delete_account_password])
        flash[:notice] = "User Account Successfully Deleted"
        redirect_to root_path
      else
         flash[:warning] = "Please Enter Correct Account Password to Delete Account"
         redirect_to edit_user_account_registration_path(current_user_account.id)
      end
  end


  def configure_sign_up_params
    attrs = [:name,:childname,:childgrade, :homeaddress]
    devise_parameter_sanitizer.permit(:sign_up, keys: attrs)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    attrs = [:name,:childname,:childgrade, :homeaddress]
    devise_parameter_sanitizer.permit(:account_update, keys: attrs)
  end

end

app/controllers/user_accounts/sessions_controller.rb
class UserAccounts::SessionsController < Devise::SessionsController
end

app/controllers/user_accounts/unlocks_controller.rb
class UserAccounts::UnlocksController < Devise::UnlocksController
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  def index
    @user_accounts = UserAccount.filter_on_constraints(constraints)
    @tograde = params[:tograde] || ""
    @fromgrade = params[:fromgrade] || ""
    @name = params[:name] || ""
    @account_type = params[:accounttype] || ""
  end

  def show
    if !current_user_account.nil?
      @user_account = current_user_account.id == params[:id] ? UserAccount.find(current_user_account.id) : UserAccount.find(params[:id])
      @requests =  @user_account.requests
    end
  end
  def email
    members = UserAccount.filter_on_constraints(constraints)
    members.each do |user|
      UserMailer.new_message(user, email_details).deliver
    end
    flash[:notice] = "Message sent to the following users"
    redirect_to user_accounts_path(:accounttype => params[:accounttype], :name => params[:name], :fromgrade => params[:fromgrade],
      :tograde => params[:tograde], :subject => params[:subject], :body => params[:body]) and return
  end

  def view
    @user_account = UserAccount.find(params[:id])
    @requests = @user_account.requests
  end

  # DELETE /resource
  def destroy
    @user_account = current_user_account.id == params[:id] ? UserAccount.find(current_user_account.id) : UserAccount.find(params[:id])
    @user_account.destroy
    flash[:notice] = "User Account Successfully Deleted"
    redirect_to root_path
  end

  private
  def constraints
    constraints = [:name, :accounttype, :fromgrade, :tograde]
    hash = {}
    constraints.each do |sym|
      hash[sym] = params[sym] if params[sym].present?
    end
    hash
  end

  def email_details
    details = [:subject, :body]
    hash = {}
    details.each do |sym|
      hash[sym] = params[sym]
    end
    hash[:from] = current_user_account.name
    hash
  end

end

app/helpers/user_account_helper.rb
module UserAccountHelper
end

app/views/user_accounts/_user_account.html.haml
%h1.header= "Account Details for #{@user_account.name}"

%table.useraccount
  %tr
    .user= "Email: "+@user_account.email
  %tr
    .user= "Name: "+@user_account.name
  %tr
    .user= "Child's Name: "+@user_account.childname.to_s
    - @user_account.childgrade == 0 ? childgrade = "" : childgrade =  @user_account.childgrade
    .user= "Child's Grade: "+childgrade.to_s
  %tr
    .user= "Address: "+@user_account.homeaddress.to_s

  %h1.header= "Requests submitted for #{@user_account.name}"
  %table.table
    %thead
      %tr
        %th Request Name
        %th Project Description

    %tbody
      -@requests.each do |request|
        %tr.request
          %td.projectname= link_to(request.projectname, request_path(request))
          %td.projectdesc= request.description

app/views/user_accounts/index.html.haml

#main.container

  %h3.header.centered_text PTO members
  %br
  .row
    .col-md-6.form_styling.input
      = form_tag user_accounts_path, :method => :get do
        = label_tag :name, "Name"
        %br
        = text_field_tag :name, @name
        %br
        = label_tag :accounttype, "Account type"
        %br
        = text_field_tag :accounttype, @accounttype
        %br
        = label_tag :fromgrade, "From grade"
        %br
        = number_field_tag :fromgrade, @fromgrade
        %br
        = label_tag :tograde, "To grade"
        %br
        = number_field_tag :tograde, @tograde
        %br
        %br
        = submit_tag "Refine the list of members"
      %br
      %br
    .col-md-6.form_styling.input
      = form_tag email_user_accounts_path, :method => :get do
        = label_tag :subject, "Subject"
        %br
        = text_field_tag :subject
        %br
        = label_tag :body, "Body"
        %br
        = text_area_tag :body
        %br
        = hidden_field_tag :name, params[:name]
        = hidden_field_tag :accounttype, params[:accounttype]
        = hidden_field_tag :fromgrade, params[:fromgrade]
        = hidden_field_tag :tograde, params[:tograde]
        %br
        = submit_tag "Send message to members shown"
  %br
  .row
    .col-md-12
      %table#events_style
        %thead
          %tr
            %th Name
            %th Email
            %th Child's Grade
            %th Account type


        %tbody
          -@members.each do |member|
            %tr.member
            %td.name= member.name
            %td.email= member.email
            %td.grade= member.childgrade
            %td.type= member.accounttype


app/views/user_accounts/members.html.haml
#main.container

  %h3.header PTO members

  = form_tag members_user_accounts_path, :method => :get do
    = label_tag :name, "Name"
    = text_field_tag :name
    = label_tag :accounttype, "Account type"
    = text_field_tag :accounttype
    = label_tag :fromgrade, "From grade"
    = number_field_tag :fromgrade
    = label_tag :tograde, "To grade"
    = number_field_tag :tograde
    = submit_tag "Refine the list of members"


  %table.table
    %thead
      %tr
        %th Name
        %th Email
        %th Child's Grade
        %th Account type


    %tbody
      -@members.each do |member|
        %tr.member
        %td.name= member.name
        %td.email= member.email
        %td.grade= member.childgrade
        %td.type= member.accounttype

  = form_tag email_user_accounts_path, :method => :get do
    = label_tag :sender, "Your name", :required => true
    = text_field_tag :sender
    = label_tag :subject, "Subject", :required => true
    = text_field_tag :subject
    = label_tag :body, "Body", :required => true
    = text_area_tag :body
    = hidden_field_tag :name, params[:name]
    = hidden_field_tag :accounttype, params[:accounttype]
    = hidden_field_tag :fromgrade, params[:fromgrade]
    = hidden_field_tag :tograde, params[:tograde]
    = submit_tag "Send message to members shown"

app/views/user_accounts/new.html.haml
#main.container
  %h1.header= 'Welcome to Hamilton Central School Parent Teacher Website'

  %h2.create_header= 'Create a new Account'
  =form_for @user_account, :method => :post do |f|

    .field
      =f.label :name, "Full Name"
      =f.text_field :name, :required => true

    .field
      =f.label :password, "Password"
      =f.password_field :password, :required => true


    .field
      =f.label :password_confirmation, "Confirm Password"
      =f.password_field :password_confirmation, :required => true


    .field
      =f.label :email, "Email"
      =f.text_field :email, :required => true


    .action
      =f.submit "Create User Account"

app/views/user_accounts/show.html.haml
#main.container
  =render "user_account"
  .row
    .col-md-2= link_to('Edit Profile Details', edit_user_account_registration_path(@user_account))

app/views/user_accounts/show_user.html.haml
#main.container
  =render "user_account"

  .row
    .col-md-2= link_to('Delete User Account', user_account_path(@user_account), method: :delete, data: {confirm: "You sure?"})
    .col-md-2= link_to('Edit Profile Details', edit_user_account_registration_path(@user_account))

app/views/user_accounts/view.html.haml
#main.container
  =render "user_account"

  .row
    .col-md-2= link_to('Delete User Account', user_account_path(@user_account), method: :delete)