config/routes.rb
Rails.application.routes.draw do

  devise_for :user_account, :controllers => {
    :registrations => 'user_accounts/registrations', :sessions => 'user_accounts/sessions'}
  resources :calendar_events do
    member do
      get 'volunteer_signup'
      get 'show_volunteer_list'
      get "email_volunteer_list"
    end
  end
  root "home#index"

  resources :user_accounts do
    collection do
      get "email"
    end
    member do
      get "view"
    end
  end

  # render static pages
  controller :pages do
    get ':id', to: 'pages#show', as: 'pages'
  end


  resources :requests




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar_event.rb
class CalendarEvent < ApplicationRecord
  has_and_belongs_to_many :user_accounts
  has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>" }, :default_url => "default_image_event.png"
validates_attachment :image, :content_type => {:content_type => ["image/jpeg", "image/png", "image/gif"]}


  scope :event_between, -> (start_date, end_date) {
    if start_date.blank? && end_date.present?
      where("end_date_time < ?", DateTime.parse(end_date).next_day)
    elsif start_date.present? && end_date.blank?
      where("start_date_time >= ?", DateTime.parse(start_date))
    else
      where("start_date_time >= ? AND end_date_time <= ?", DateTime.parse(start_date), DateTime.parse(end_date))
    end
  }

  scope :future_event, -> {where('start_date_time >= ?', DateTime.now)}

  scope :approved_upcoming, -> (lim) {approved_confirmed.future_event.order("start_date_time desc").limit(lim)}

  scope :find_approved, -> (is_approved) {where("is_approved = ?", is_approved)}

  scope :approved_confirmed, -> {find_approved(true)}

  scope :approved_pending, -> {find_approved(false)}

  def start_date
    self.start_date_time.to_date
  end

  def end_date
    self.end_date_time.to_date
  end

  def start_time
    self.start_date_time.strftime('%l.%M %p')
  end

  def end_time
    self.end_date_time.strftime('%l.%M %p')
  end
end

app/controllers/calendar_events_controller.rb
require 'date'

class CalendarEventsController < ApplicationController

  def index
    if !current_user_account.try(:admin?)
      @calendar_events = CalendarEvent.where('is_approved = ?', true)
    end 
    @start_date_time = params[:start_date_time] || ""
    @end_date_time = params[:end_date_time] || ""
    @calendar_events = @calendar_events.event_between(params[:start_date_time],params[:end_date_time]) if params[:start_date_time].present? || params[:end_date_time].present?
    order = params[:order] || :start_date_time
    @calendar_events = @calendar_events.order(order)
  end

  def show
    id = params[:id]
    @user_account = session[:user]
    @calendar_event = CalendarEvent.find(id)
  end

  def create
    @calendar_event = CalendarEvent.new(create_update_params)
    @calendar_event.start_date_time = @calendar_event.start_date_time.to_formatted_s(:short)
    @calendar_event.end_date_time = @calendar_event.end_date_time.to_formatted_s(:short)
    if @calendar_event.save
      if @calendar_event.is_approved
        flash[:success] = "New event \'#{@calendar_event.title}\' created and added to the page"
      else
        flash[:notice] = "New event \'#{@calendar_event.title}\' awaiting approval"
      end
      redirect_to calendar_events_path
    else
      flash[:warning]= "Error creating new event"
      redirect_to new_calendar_event_path(@calendar_event)
    end
  end

  def edit
    id = params[:id]
    @user_account = session[:user]
    @calendar_event = CalendarEvent.find(id)
  end

  def update
    id = params[:id].to_i
    @calendar_event = CalendarEvent.find(id)

    @calendar_event.update(create_update_params)
    if @calendar_event.save
      flash[:success] = "Event \'#{@calendar_event.title}\' updated"
      redirect_to calendar_event_path(@calendar_event) and return
    else
      flash[:error] = "Error updating event"
      redirect_to edit_calendar_event_path(@calendar_event) and return
    end
  end

  def new
    @user_account = session[:user]
    @calendar_event = CalendarEvent.new
  end

  def volunteer_signup
    if current_user_account.nil?
      flash[:error] = "You need to sign in to volunteer"
      redirect_to calendar_event_path
    else
      @new_volunteer = UserAccount.find(current_user_account.id)
      @calendar_event =  CalendarEvent.find(params[:id])
      @calendar_event.user_accounts << @new_volunteer
      flash[:notice] = "You have signed up to volunteer for \'#{@calendar_event.title}\'. Event will take place on #{@calendar_event.start_date_time}."
      redirect_to calendar_event_path(@calendar_event)
    end
  end

  def show_volunteer_list
    @calendar_event =  CalendarEvent.find(params[:id])
    # decided to hide the button for non-admins
    # if current_user_account.nil?
    #   flash[:error] = "You need to sign in to see the volunteer list"
    #   redirect_to calendar_event_path(@calendar_event) and return
    # end
  end

  def email_volunteer_list
    @calendar_event = CalendarEvent.find(params[:id])
    @calendar_event.user_accounts.each do |user|
      UserMailer.new_message(user, email_details).deliver
    end
    flash[:notice] = "Message sent to the following users"
    redirect_to show_volunteer_list_calendar_event_path(@calendar_event)
  end



  def destroy
    id = params[:id]
    @calendar_event = CalendarEvent.find(id)
    @calendar_event.destroy
    flash[:notice] = "Event \'#{@calendar_event.title}\' deleted"
    redirect_to calendar_events_path
  end

  private
  def create_update_params
    params.require(:calendar_event).permit(:title, :start_date_time, :end_date_time, :location, :description, :is_sport, :is_musical, :is_meeting, :is_charity, :is_gathering, :is_optional, :for_teacher, :for_parent, :for_elementary_student, :for_highschool_student, :contact_person, :is_approved, :image)
  end

  def email_details
    details = [:subject, :body]
    hash = {}
    details.each do |sym|
      hash[sym] = params[sym]
    end
    hash[:from] = current_user_account.name
    hash
  end

end

app/views/calendar_events/_event_form_template.html.haml
.field
  =f.label :title, "Title"
  =f.text_field :title, required: true, class: 'form-template'

.field
  =f.label :description, "Description"
  =f.text_field :description, required: true, class: 'form-template'

.field
  =f.label :location, "Location"
  =f.text_field :location, required: true, class: 'form-template'

.field
  =f.label :start_date_time, "Start date of the event"
  =f.datetime_local_field :start_date_time, required: true, class: 'form-template', min: Date.today

.field
  =f.label :end_date_time, "End date of the event"
  =f.datetime_local_field :end_date_time, required: true, class: 'form-template', min:Date.today

.field
  =f.label :is_sport
  =f.check_box :is_sport, class: 'form-template'

.field
  =f.label :is_musical
  =f.check_box :is_musical, class: 'form-template'

.field
  =f.label :is_meeting
  =f.check_box :is_meeting, class: 'form-template'

.field
  =f.label :is_charity
  =f.check_box :is_charity, class: 'form-template'

.field
  =f.label :is_gathering
  =f.check_box :is_gathering, class: 'form-template'

.field
  =f.label :is_optional
  =f.check_box :is_optional, class: 'form-template'

.field
  =f.label :for_teacher
  =f.check_box :for_teacher, class: 'form-template'

.field
  =f.label :for_parent
  =f.check_box :for_parent, class: 'form-template'

.field
  =f.label :for_elementary_student
  =f.check_box :for_elementary_student, class: 'form-template'

.field
  =f.label :for_family
  =f.check_box :for_family, class: 'form-template'

.field
  =f.label :for_highschool_student
  =f.check_box :for_highschool_student, class: 'form-template'

.field
  =f.label :contact_person, "Contact person email"
  =f.text_field :contact_person, required: true, class: 'form-template'

.field
  =f.label :image, "Image"
  =f.file_field :image, accept: "image/png,image/gif,image/jpeg"

-# .field
-#   =f.label :is_approved, "Is this event approved?"
-#   =f.check_box :is_approved, class: 'form-template'

-# TODO for futre implementation with authorization
-if current_user_account.admin
  .field.form-group
    = f.label :is_approved, "Is the event approved?"
    -if @calendar_event.is_approved
      = f.check_box :is_approved, :checked => (f.is_approved ? f.is_approved : false), required: true
    -else
      =f.check_box :is_approved, :checked =>false, required: false

-else
  .field.form-group
    = f.hidden_field :is_approved, :value => false, required: false

app/views/calendar_events/edit.html.haml
#main.container
  %h3.header Edit event details

  =form_for @calendar_event, :method => :patch do |f|
    =render 'event_form_template', f: f

    .field
      =f.submit "Update event details"

app/views/calendar_events/index.html.haml
%div
  #main.container
  %br
  %br

    .row
      .col-md-1
      %h3.col-md-3.header Calendar Events
      .col-md-3
      .col-md-2=link_to "Create a new event for HCS-PTO", new_calendar_event_path, :class => "btn btn-success btn-lg"
      .col-md-3

    %br
    %table.table#events_style
      %thead
        %tr
          %th= link_to('Title',calendar_events_path(:order => 'title'))
          %th Description
          %th= link_to('Location', calendar_events_path(:order => :location))
          %th= link_to('Contact Person', calendar_events_path(:order => :contact_person))
          %th= link_to('Start Date', calendar_events_path(:order => :start_date_time))
          %th= link_to('End Date', calendar_events_path(:order => :end_date_time))
          %th Start Time
          %th End Time
          %th Volunteer
      %tbody
        -@calendar_events.each do |event|
          %tr.event
          %td.title=link_to event.title, calendar_event_path(event)
          %td.description=truncate(event.description, length: 50)
          %td.location=event.location
          %td.contact_person=event.contact_person
          %td.date=event.start_date_time ? event.start_date: "No date indicated"
          %td.date=event.end_date_time ? event.end_date: "No date indicated"
          %td.time=event.start_date_time ? event.start_time: "No time indicated"
          %td.time=event.end_date_time ? event.end_time: "No time indicated"
          %td.volunteer_signup=link_to("Sign up for #{event.title} ", volunteer_signup_calendar_event_path(event))

    = form_tag calendar_events_path, :method => :get do
      = label_tag :start_date_time, "From"
      = date_field_tag :start_date_time, @start_date_time

      = label_tag :end_date_time, "To"
      = date_field_tag :end_date_time, @end_date_time

      = submit_tag "Show events"
    %br
    %br

app/views/calendar_events/new.html.haml
#main.container
%br
%br

%h3.header Create a new calendar event to list

=form_for @calendar_event, :method => :post do |f|
  =render 'event_form_template', f: f

  .field
    =f.submit "Create event"

app/views/calendar_events/show.html.haml
#main.container
  %br
  %br

  .row
    .col-sm-2
    .col-sm-8
      %h3.header.title= "#{@calendar_event.title}"
    .col-sm-offset-1

  .row
    .col-sm-8.image= image_tag @calendar_event.image.url(:medium)

  %br

  .row
    .col-sm-offset-8
    .col-sm-8.description= "#{@calendar_event.description}"

  .row
    .col-sm-offset-2
    .col-sm-8.date_time= "Start date and time: #{@calendar_event.start_date_time ? @calendar_event.start_date_time.to_formatted_s(:short): "No time indicated"}"
  .row
    .col-sm-offset-2
    .col-sm-8.date_time= "End date and time: #{@calendar_event.end_date_time ? @calendar_event.end_date_time.to_formatted_s(:short): "No time indicated"}"
  .row
    .col-sm-offset-2
    .col-sm-8.location= "The event is at #{@calendar_event.location}."
  .row
    .col-sm-8.contact_person= "#{@calendar_event.contact_person} is the contact person for this event."

  %br
  %br

  .row
    .col-sm-offset-1
    .col-sm-2= link_to 'Back to events list', calendar_events_path, :class => "btn btn-primary btn-md"
    .col-sm-2= link_to 'Sign up to volunteer for this event', volunteer_signup_calendar_event_path, :class => "btn btn-success btn-md"
    -if !current_user_account.nil? and current_user_account.admin
      .col-sm-2= link_to('Show volunteers list', show_volunteer_list_calendar_event_path)
      .col-sm-2= link_to('Edit event details', edit_calendar_event_path(@calendar_event))
      .col-sm-2= link_to('Delete event', calendar_event_path(@calendar_event), :method => :delete)

app/views/calendar_events/show_volunteer_list.html.haml
#main.container
  %br
  %br

  .row
    .col-md-offset-1
    .col-md-4
      %h2.header.title= "#{@calendar_event.title}"
    .col-md-offset-2
    .col-md-4.centered_text.date_time= "Start date and time: #{@calendar_event.start_date_time ? @calendar_event.start_date_time.to_formatted_s(:short): "No time indicated"}"
    .col-md-4.centered_text.contact_person= "#{@calendar_event.contact_person} is the contact person for this event."
    .col-md-offset-4
    %h4 Volunteer List
  %table.table#events_style
    //%caption Volunteer List
    %thead
      %tr
        %th Name
        %th Email
    %tbody
      -@calendar_event.user_accounts.each do |user|
        %tr.event
        %td.name=link_to(user.name, view_user_account_path(user))
        %td.email=user.email
    %br
    %br

  .row
    .col-md-offset-1

    .col-md-2.centered_text.shaded_green= link_to('Back to events list', calendar_events_path)

= form_tag email_volunteer_list_calendar_event_path(@calendar_event), :method => :get do
  = label_tag :subject, "Subject"
  = text_field_tag :subject
  %br
  = label_tag :body, "Body"
  = text_area_tag :body
  %br
  = submit_tag "Send message to members shown"
