config/routes.rb
Rails.application.routes.draw do

  devise_for :user_account, :controllers => {
    :registrations => 'user_accounts/registrations', :sessions => 'user_accounts/sessions'}
  resources :calendar_events do
    member do
      get 'volunteer_signup'
      get 'show_volunteer_list'
      get "email_volunteer_list"
    end
  end
  root "home#index"

  resources :user_accounts do
    collection do
      get "email"
    end
    member do
      get "view"
    end
  end

  # render static pages
  controller :pages do
    get ':id', to: 'pages#show', as: 'pages'
  end


  resources :requests




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @calendar_events = CalendarEvent.approved_upcoming(4); # can be nil
    # current_user_account.update_attribute(:admin, true) if !current_user_account.nil?
  end
end

app/views/home/index.html.haml
#main

  %div.carousel.slide{ "data-ride" => "carousel", :id => 'homepage__image-carousel'}
    // Indicators
    %ol.carousel-indicators
      %li.active{"data-target" => "#homepage__image-carousel", "data-slide-to"=>"0"}
      %li{"data-target" => "#homepage__image-carousel", "data-slide-to"=>"1"}
      %li{"data-target" => "#homepage__image-carousel", "data-slide-to"=>"2"}

    // Wrapper for slides
    %div.carousel-inner{ :role => "listbox" }
      // Slide One
      %div.carousel-item.active.crop=image_tag 'emerald.png', :class => "d-block w-100"
      .container
        .carousel-caption

          .homepage__carousel__title Hamilton Central Parent Teacher Organization
          .homepage__carousel__description Welcome to the official webpage of the Hamilton Central Parent Teacher Organization. Learn more about how you can be involved with the group, or understand more about us.
          %h1 Hamilton Central Parent Teacher Organization

          %p.lead Welcome to the official webpage of the Hamilton Central Parent Teacher Organization. Learn more about how you can be involved with the organization, or understand more about us.

          =link_to "Understand HC PTO Better", pages_path(:about), :class => "btn btn-success btn-lg"

      // Slide Two
      %div.carousel-item.img-fluid.crop=image_tag 'slideshow2.jpg', :class => "d-block w-100"
      // Slide Three
      %div.carousel-item.img-fluid.crop=image_tag 'slideshow3.jpg', :class => "d-block w-100"

    // Controls
    .carousel-control-prev{:href => "#homepage__image-carousel", :role => "button", 'data-slide'=>"prev"}
      %span.carousel-control-prev-icon
      %span.sr-only Previous
    .carousel-control-next{:href => "#homepage__image-carousel", :role => "button", 'data-slide'=>"next"}
      %span.carousel-control-next-icon
      %span.sr-only Next

%br
.container
  %h2 Upcoming events
  %hr

  %div.row.card-set
    -@calendar_events.each do |event|
      .col-lg-4.col-md-6.col-sm-12.card-set.homepage__event
        / Add a line to separate between events
        %card.mb-4
          .card-img-top=image_tag event.image.url(:medium)
          -# Card body, containing title and description
          .card-body
            .homepage__event__title.title=link_to event.title, calendar_event_path(event)
            .card-text
              .homepage__event__description.description=truncate(event.description, length: 40)
              .homepage__event__description.contact=event.contact_person
          .card-footer.homepage__event__footer
            .row
              .col-sm-4=event.start_date_time ? event.start_date: "No date indicated"
              .col-sm-4=event.start_date_time ? event.start_time: "No time indicated"
              .col-sm-4=event.location

  %br
  %br