config/routes.rb
Rails.application.routes.draw do

  devise_for :user_account, :controllers => {
    :registrations => 'user_accounts/registrations', :sessions => 'user_accounts/sessions'}
  resources :calendar_events do
    member do
      get 'volunteer_signup'
      get 'show_volunteer_list'
      get "email_volunteer_list"
    end
  end
  root "home#index"

  resources :user_accounts do
    collection do
      get "email"
    end
    member do
      get "view"
    end
  end

  # render static pages
  controller :pages do
    get ':id', to: 'pages#show', as: 'pages'
  end


  resources :requests




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_message.html.haml
-if flash[:notice]
  .alert.alert-info= flash[:notice]
-if flash[:error]
  .alert.alert-danger= flash[:error]
-if flash[:success]
  .alert.alert-success= flash[:success]
-if flash[:warning]
  .alert.alert-danger= flash[:warning]

app/views/application/_navbar.html.haml
-# // # is id, must be unique
-# // . for class
-# // % for tag

%nav.navbar.navbar-expand.navbar-dark.flex-column.flex-md-row.bg-emerald
  = link_to "HCS-PTO", root_path, :class => "navbar-brand mr-0 mr-md-2"
  %div.navbar-nav-scroll
    %ul.navbar-nav
      -if !current_user_account.nil?
        -if current_user_account.admin?
          %li.nav-item
            =link_to "User Accounts", user_accounts_path, :class => 'nav-link'
      %li.nav-item
        =link_to "Events", calendar_events_path, :class => 'nav-link'
      %li.nav-item
        =link_to "Clubs and Organizations", pages_path(:clubs), :class => 'nav-link'
      %li.nav-item
        =link_to "Create a Request", new_request_path, :class => 'nav-link'
      %li.nav-item
        =link_to "About", pages_path(:about), :class => 'nav-link'
  %ul.navbar-nav.flex-row.ml-md-auto.d-none.d-md-flex
    -if !current_user_account.nil?
      %li.nav-item
        =link_to "Hello, #{current_user_account.name}", user_account_path(current_user_account), :class => 'nav-link p-2'
      %li.nav-item
        =link_to "Log Out", destroy_user_account_session_path, method: :delete, :class => 'nav-link p-2'
    -else
      %li.nav-item
        =link_to "Sign In", new_user_account_session_path, :class => 'nav-link p-2'
      %li.nav-item
        =link_to "Sign Up", new_user_account_registration_path, :class => 'nav-link p-2'